### PR TITLE
Convert pivoted CSV's to libSVM format

### PR DESCRIPTION
**Pull request by henrique**
" It can also input typical pivoted SQL like CSV in the form of `sampleID, colIndex [, label]` if _pivot index_ is defined pointing to _colIndex_. "

### CODE REVIEW

**Comment by zygmuntz** [comment]
Please convert indentation to tabs and follow `( spaces between parens and content )` convention, if it's not to big a problem.

Also, a sample of how the input data might look like would be welcome (in the source comments).

**Comment by henrique** [comment]
Hi Zygmunt,
Was this what you meant? Sorry for the long delay
Cheers,
Henrique
ps.: the first commit also fixes the other pull request #4

**Comment by zygmuntz** [comment]
After reviewing the changes, I came to the conclusion that handling pivoted csv is best done in a separate script: https://github.com/zygmuntz/phraug/blob/master/pivotedcsv2libsvm.py

Your implementation stored all lines in memory, which doesn't comply with the online nature of _phraug_.

I'm curious about labels in pivoted csv, are they supposed to be always 1?

**Comment by henrique** [comment]
Hi Zygmunt,
Thanks for having a look and merging it.
I bet you had a great performance improvement on your implementation but I actually use uid's for the features so it does read work for my dataset
e.g.:
input example:
id1,f1
id1,f2
id1,f3
id2,f2,0.5
id2,f3,0.6
id2,f4,0.7

output example:
1 f2:1 f3:1 f4:1
1 f3:0.5 f4:0.6 f5:0.7

**Comment by henrique** [comment]
I don't really care much about the svm labels because I actually use "generator" just after this to transform:
1 f3:0.5 f4:0.6 f5:0.7

into:
f3 f4:0.6 f5:0.7
f4 f3:0.5 f5:0.7
f5 f3:0.5 f4:0.6

for multiclass classification... I haven't shared it yet mainly because it might be quite specific to my use case and also because I don't really have a good name for it hehe

**Comment by zygmuntz** [comment]
I see... But that's not _libsvm_ format, it does seem specific to your case.

**Comment by henrique** [comment]
Yes you're right I should have converted everything to ints beforehand

**Pull request merged**
